### ISSUE TITLE
Parser completeness

### ISSUE THREAD

**Issue by meakbiyik** [r-lib/tree-sitter-r#1]
Hi, first of all thanks for the good work! I wish to use your parser to implement a VSCode test suite extension for testthat framework, but could not be sure if the parser is complete. Are there any known issues at this point? If so, I can also pitch in, I have already written a tree-sitter grammar before.

**Comment by jimhester** [comment]
I tested this with all of the base and recommended packages that come with R as well as those in the tidyverse and r-lib GitHub repositories. I cannot 100% guarantee the correctness of all the parsing for all these cases, but it is able to parse them without error.

**Comment by jimhester** [comment]
That being said if you find an issue and would like to help improve the parser that would be great!

**Comment by meakbiyik** [comment]
That sounds pretty extensive in any case, and should certainly work for my purposes since I will only run the parser on the files using testthat. Thanks a lot!
