### ISSUE TITLE
Support for nvim-treesitter-textobjects

### ISSUE THREAD

**Issue by mllg** [r-lib/tree-sitter-r#10]
First, thanks for your work on supporting R in treesitter.

I wonder if support for text objects (https://github.com/nvim-treesitter/nvim-treesitter-textobjects) is currently possible. The required files to extend a language with textobjects are located in `queries/[language]`, e.g. https://github.com/nvim-treesitter/nvim-treesitter-textobjects/blob/master/queries/c/textobjects.scm for C.

In particular, @parameter.inner and @parameter.outer would be interesting for me, but I think most objects have their raison d'être. I had a quick look in the code, but I didn't find a named node for it.

**Comment by jimhester** [comment]
Sure it is possible, someone would need to write the queries like you linked to.

`@parameter.inner` would likely be variations on this

```
(formal_parameters
  (identifier) @parameter.inner)
```

**Comment by aspeddro** [comment]
@mllg, https://github.com/nvim-treesitter/nvim-treesitter-textobjects/pull/173 added support for r

**Comment by jimhester** [comment]
Great, thanks @aspeddro!

**Comment by mllg** [comment]
Thanks!

AFAICT @parameter.inner and @parameter.outer only work in the function definition (`|` is cursor position):

```r
# works here
f = function(x|, y, ...) {
  x^2
}

# does not work here
f(x|, y)
```

Is this working as intended or am I mixing things up?

**Comment by aspeddro** [comment]
@mllg, https://github.com/nvim-treesitter/nvim-treesitter-textobjects/pull/181 add support to call functions.
