### ISSUE TITLE
Bug: incorrect highlighting/indentation with some if-statements

### ISSUE THREAD

**Issue by wurli** [r-lib/tree-sitter-r#103]
This seems to occur when braces aren't used:

![image](https://github.com/r-lib/tree-sitter-r/assets/17475731/9d840990-95b6-4a2a-baae-8fe5334c3266)

The above screenshot is from Neovim using treesitter for highlighting and indentation. The text after this block is also shown as a syntax error, presumably due to the same issue.

Thanks for the work maintaining this grammar!

**Comment by DavisVaughan** [comment]
Is that "top level" code, or is it inside a function / anything with braces `{ }`?

It is illegal in R to have an if/else at the top level where an `else` is on its own line, unless you are already wrapped in `{ }`

Like, this works

```
if (TRUE) x <- 1 else x <- 2
```

and this works

```
{
  if (TRUE) 
    x <- 1 
  else 
    x <- 2
}
```

But this does not

```
if (TRUE) 
  x <- 1 
else 
  x <- 2
```

(yes this is somewhat crazy)

**Comment by wurli** [comment]
Wow - it's been a while since I've learnt something this weird about R!

Enclosing with braces removes the syntax errors in subsequent code, but unfortunately highlighting and indentation still appear to be off. This shows the results after treesitter-powered auto-indentation:
![image](https://github.com/r-lib/tree-sitter-r/assets/17475731/146891c7-3d13-437a-bb2e-a37cb64c085d)

**Comment by DavisVaughan** [comment]
It is likely this has been fixed in the next branch, we did do some work to improve on if/else statements like this there recently

**Comment by wurli** [comment]
Many thanks!

**Comment by DavisVaughan** [comment]
I'm somewhat confident this is not an issue in `next`.

The following:

```
{
 if (TRUE) 
   x <- 1 
 else 
   x <- 2
}
```

produces this on `main`

```
(program [0, 0] - [5, 1]
  (brace_list [0, 0] - [5, 1]
    (if [1, 1] - [2, 9]
      condition: (true [1, 5] - [1, 9])
      consequence: (left_assignment [2, 3] - [2, 9]
        name: (identifier [2, 3] - [2, 4])
        value: (float [2, 8] - [2, 9])))
    (identifier [3, 1] - [3, 5])
    (left_assignment [4, 3] - [4, 9]
      name: (identifier [4, 3] - [4, 4])
      value: (float [4, 8] - [4, 9]))))
```

which is wrong. Note how `(if [1, 1] - [2, 9]` doesn't span the whole if statement.

Compare to `next`

```
(program [0, 0] - [5, 1]
  (braced_expression [0, 0] - [5, 1]
    body: (if_statement [1, 1] - [4, 9]
      condition: (true [1, 5] - [1, 9])
      consequence: (binary_operator [2, 3] - [2, 9]
        lhs: (identifier [2, 3] - [2, 4])
        rhs: (float [2, 8] - [2, 9]))
      alternative: (binary_operator [4, 3] - [4, 9]
        lhs: (identifier [4, 3] - [4, 4])
        rhs: (float [4, 8] - [4, 9])))))
```

Note `(if_statement [1, 1] - [4, 9]` that covers the right ranges
