### ISSUE TITLE
R CMD check produces a NOTE: "Files which contain pragma(s) suppressing diagnostics"

### ISSUE THREAD

**Issue by etiennebacher** [r-lib/tree-sitter-r#130]
Hi, I'm making a package that builds on `tree-sitter-r` ([`astgrepr`](https://github.com/etiennebacher/astgrepr/)). R-CMD-check works fine except for a NOTE:

```
N  checking pragmas in C/C++ headers and code (904ms)
   Files which contain pragma(s) suppressing diagnostics:
     'src/vendor/tree-sitter-r/src/parser.c'
     'src/vendor/tree-sitter-r/src/tree_sitter/array.h'
```
I'm using the latest crate available at the time of writing (1.0.1). Should this be fixed here? 

Thanks!

---

Edit: this only appears on Windows: https://github.com/etiennebacher/astgrepr/actions/runs/9775182731/job/26985038631#step:6:126

**Comment by DavisVaughan** [comment]
This is only something that CRAN cares about, so you have to patch it yourself. i.e. like I do in {treesitter.r}
https://github.com/r-lib/tree-sitter-r/blob/b1e211f52ad8f8e1e182bbbcc16dcd5e3688eb7d/bindings/r/bootstrap.R#L127

**Comment by DavisVaughan** [comment]
Oh you're using the rust crate directly? And I guess that compiles it (and the C code with the pragmas) on the fly during R package building. Hmm, that makes it tricker i guess. I guess you have two options:
- Patch the rust crate after it is downloaded if possible
- Vendor the `parser.c`, `scanner.c`, and `tree_sitter/` headers like I do in treesitter.r and patch them yourself, then compile that C code and call it from Rust

**Comment by DavisVaughan** [comment]
I would also highly recommend not pinning to our `main` branch https://github.com/etiennebacher/astgrepr/blob/5f0597c09c9a805a6f22a9deff2743c659c1dff5/src/rust/Cargo.toml#L20

If you are going to use the tree-sitter-r Rust crate, pin to a release https://crates.io/crates/tree-sitter-r or at least pin to a specific github commit so you can incorporate any grammar changes at your own pace

**Comment by etiennebacher** [comment]
> I would also highly recommend not pinning to our main branch 

Thanks, fixed

> I guess you have two options:
>
> *  Patch the rust crate after it is downloaded if possible
> * Vendor the parser.c, scanner.c, and tree_sitter/ headers like I do in treesitter.r and patch them yourself, then compile that C code and call it from Rust

Maybe this is feasible but it sounds complicated for a NOTE only. I tried to fix it in https://github.com/etiennebacher/astgrepr/commit/480bf65d52463a28aabbd7ee64838f4c1b4e3b50 but it doesn't work I'll just try to negotiate with the CRAN team.

**Comment by DavisVaughan** [comment]
Historically in other packages we have also been forced to work around this note sadly 😞

**Comment by etiennebacher** [comment]
Ah, too bad. And just to clarify, wouldn't it be possible to remove those `#pragma` lines before publishing the crate on crates.io? I've never made packages interacting with low-level languages so I'm completely in foreign territory here

**Comment by DavisVaughan** [comment]
I believe the pragmas actually do matter and are being used, adding the space between `#` and `pragma` just happens to get rid of the CRAN note.

And I'd really like tree-sitter-r to be "just another tree sitter grammar" with no extra patches within the grammar itself, so that it is extremely closely aligned with the rest of the tree sitter ecosystem. So patching within the R package seems like the best option to me, because other consumers of the C files don't seem to care about pragmas. Alternatively you can ask the upstream tree-sitter group if the pragmas are really needed (it is their tool that generates the pragmas, not us), but I imagine they are

**Comment by etiennebacher** [comment]
My patch [didn't work](https://github.com/etiennebacher/astgrepr/actions/runs/9778810601/job/26996488777#step:6:126), but I don't understand why since the `# pragma` lines were correctly removed from the two files indicated in the NOTE.

Anyway, I understand, this is not something to be fixed here, thank you for your answers.
