### ISSUE TITLE
Maybe related - nvim-treesitter error after updating R treesitter parser version

### ISSUE THREAD

**Issue by Tal500** [r-lib/tree-sitter-r#131]
See https://github.com/nvim-treesitter/nvim-treesitter/issues/7001, I don't know if related

**Comment by DavisVaughan** [comment]
Seems like you got it fixed

**Comment by Tal500** [comment]
> Seems like you got it fixed

No it's not, it's just moving to `nvim-treesitter-textobjects` now, can you please reopen?

**Comment by DavisVaughan** [comment]
I see

```
treesitter/query.lua:252: Query error at 12:2. Invalid node type "if":
```

That seems to suggest that neovim is writing a query against the old version of tree-sitter-r

I know they were working on this though, so it seems like you need to update nvim-treesitter or something, see https://github.com/nvim-treesitter/nvim-treesitter/pull/6774

But it is not a tree-sitter-r issue

**Comment by DavisVaughan** [comment]
It seems like this PR would solve your issue https://github.com/nvim-treesitter/nvim-treesitter-textobjects/pull/645

**Comment by Tal500** [comment]
> It seems like this PR would solve your issue [nvim-treesitter/nvim-treesitter-textobjects#645](https://github.com/nvim-treesitter/nvim-treesitter-textobjects/pull/645)

Verified and it works!
