### ISSUE TITLE
error native pipe operator

### ISSUE THREAD

**Issue by aspeddro** [r-lib/tree-sitter-r#14]
![image](https://user-images.githubusercontent.com/16160544/133538618-58172700-9cb8-40a1-bc7a-cd7fd4a9d224.png)

```plaintext
NVIM v0.5.0
Build type: Release
LuaJIT 2.0.5
```

**Comment by jimhester** [comment]
Yep, it is currently not supported in the parser.

**Comment by jimhester** [comment]
Fixed by https://github.com/r-lib/tree-sitter-r/pull/15
