### ISSUE TITLE
Consider simplifying `parenthesized_expression`

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/tree-sitter-r#144]
https://github.com/r-lib/tree-sitter-r/blob/4279b699c47fa87956045980c46c7d30f8c0121b/grammar.js#L282-L286

- I don't think the `$._newline` is doing anything. The external scanner consumes newlines proactively when you are within `()` (unlike `{` for `braced_expression`, where it is needed)
- I think we should also limit it to exactly 1 `field("body", $._expression)`, rather than allowing for multiple, since R doesn't actually allow this for parenthesized expressions (note, not `optional()`! see Kevin's comments below)

**Comment by kevinushey** [comment]
In addition, `()` alone is technically a parser error -- R requires there to be exactly one expression within the parentheses. The original definition was motivated by the "permissive" style parser but it sounds like we're moving away from that.
