### ISSUE TITLE
Proposal PR: parse `T` and `F` as boolean

### ISSUE THREAD

**Issue by aspeddro** [r-lib/tree-sitter-r#18]
Currently the parser define `T` as variable, but help panel in base package show `T` and `F` as aliases to logical `TRUE` and `FALSE`.

R accept make let bindings with `T` and `F`
```r
> T == TRUE
[1] TRUE
> F == FALSE
[1] TRUE
> TRUE <- "lol"
Error in TRUE <- "lol" : invalid (do_set) left-hand side to assignment
> T <- "lol"
> T == TRUE
[1] FALSE
```
If parsing `T` and `F` as `TRUE` and `FALSE` is a good idea I can open a PR. 

RStudio currently highlights `T` and `F`

**Comment by jimhester** [comment]
I think treating them as variables is technically correct, as you observe you can assign to them like any other variable name, they just happen to have default values assigned of `TRUE` and `FALSE`.

**Comment by aspeddro** [comment]
I agree
