### ISSUE TITLE
Inconsistent grammar name

### ISSUE THREAD

**Issue by meakbiyik** [r-lib/tree-sitter-r#2]
At the current stage, trying to install this grammar via `npm install git+https://github.com/r-lib/tree-sitter-r.git` throws an error during the linking stage in Windows. 

```
binding.obj : error LNK2019: unresolved external symbol tree_sitter_R referenced in function "void __cdecl `anonymous namespace'::Init(class v8::Local<class v8::Object>,class v8:
:Local<class v8::Object>)" (?Init@?A0x7b0c94f0@@YAXV?$Local@VObject@v8@@@v8@@0@Z) [C:\Users\erena\OneDrive\Desktop\vscode-R-test-adapter\node_modules\tree-sitter-r\build\tree_sit
ter_R_binding.vcxproj]
```

The reason for this error is because the grammar names defined in grammar.js and binding.gyp are inconsistent: the former defines it as `r` while the latter uses `R`, but the compiler is not case-insensitive (at least MSBuild isn't) and since tree-sitter cli generates the C file from the grammar.js file, the exported function names are not consistent. Correcting this resolves the install error in my local.

**Comment by jimhester** [comment]
Thanks, I renamed this to use lower case R in https://github.com/r-lib/tree-sitter-r/commit/440a3088fbaf8aaaf00b6622b5423a990681cc2e, but I missed changing it in `binding.gyp`

**Comment by meakbiyik** [comment]
My bad, it seems I have also changed index.js to correct the error --I though it was a result of the tree-sitter generate. @jimhester can you also fix that file?

**Comment by jimhester** [comment]
Ok should have gotten them all now
