### ISSUE TITLE
telescope treesitter picker not working for R 

### ISSUE THREAD

**Issue by sebffischer** [r-lib/tree-sitter-r#25]
Hello, 

first of all thank you for providing treesitter support for R!

I am running into some issues when using the neovim plugin telescope. 
[nvim-treesitter](https://github.com/nvim-telescope/telescope.nvim) allows to list all treesitter symbols from the current buffer. When doing this in an R file, no symbols are displayed. It seems to be that the function treesitter.locals.get_definitions function that is called by the telescope treesitter picker (and which is located i telescope.nvim/lua/telescope/builtin/files.lua) is returning an empty table. 

I am not sure whether this is an issue here, in telescope or in treesitter, but the telescope picker "list treesitter symbols" is working for e.g. lua files and the R parser is also detected (it does not throw the warning "no parser for this filtype").

**Comment by aspeddro** [comment]
Fixed in https://github.com/nvim-telescope/telescope.nvim/issues/1631#event-5862595473

**Comment by jimhester** [comment]
From the linked issue it looks like this was fixed in nvim-telescope, so no changes are needed here. If this is not the case please comment and we can re-open the issue.
