### ISSUE TITLE
Parser cannot correctly recognize the parameters when the context is a function call

### ISSUE THREAD

**Issue by milanglacier** [r-lib/tree-sitter-r#29]
Dear Developer:
Hi! I'm using neovim's builtin treesitter, with [nvim-treesitter-textobjects](https://github.com/nvim-treesitter/nvim-treesitter-textobjects).

The following plugin can let us manipulate on the text objects based on the syntax node.

In the following example, `|` will be my cursor position:

```{r}
a = rnorm(1, 1|0)

# after typing daa at the cursor position, which means delete a argument(parameter),
# I can't get any response

a = rnorm(1, 10)

# The correct result should be

a = rnorm(1)
```

But instead, if the parameters(arguments) in a function call is variables rather than expressions, then it works:

```{r}

dog = 5
cat = 5
a = rnorm(do|g, cat)

# after typing daa at the cursor position, which means delete a argument(parameter), 
# it responses as correct result:

a = rnorm(cat)
```

and it also seems that the parser can only recognize variable as unnamed argument, it also cannot recognize
passing named argument.

```
cat = 5
dog = 20
a = rnorm(dog, me|an = cat)
# after type daa, it becomes
a = rnorm(dog, |= cat)

a = rnorm(dog, mean = c|at)
# after type daa, it becomes
a = rnorm(dog, mean =| )

# the correct result in both case should be
a = rnorm(dog )
```

minimal neovim configuration to reproduce:

firstly install `vim-plug`:

```
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
```
Then put the configurations in
`$HOME/.config/nvim/init.vim`:

```

call plug#begin()

Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
Plug 'nvim-treesitter/nvim-treesitter-textobjects'

call plug#end()

lua << EOF
require'nvim-treesitter.configs'.setup {

    ensure_installed = {"r"},

    textobjects = {
        select = {
            enable = true,
            lookahead = false,
            keymaps  = {
                ["aa"] = "@parameter.outer",
                ["ia"] = "@parameter.inner",
            }
        },
}

EOF
```

then open neovim in terminal `nvim` and run `:TSUpdate`,
then open an R file with neovim `nvim xxx.R`:

```{r}
dog = 5
cat = 5
a = rnorm(dog, cat)
a = rnorm(1, 10)
a = rnorm(dog, mean = cat)


```

**Comment by aspeddro** [comment]
@milanglacier thanks for reporting.

When I added the queries map only `identifier`, which is not correct.

https://github.com/nvim-treesitter/nvim-treesitter-textobjects/blob/7c6b5fe0926f52854f193d058cd98d2e74c3d483/queries/r/textobjects.scm#L54-L61

I'm going to open a PR to make an adjustment to the parser and once it's merged I update the query in https://github.com/nvim-treesitter/nvim-treesitter-textobjects

**Comment by aspeddro** [comment]
Fixed by https://github.com/nvim-treesitter/nvim-treesitter-textobjects/pull/194

**Comment by jimhester** [comment]
🙏
