### ISSUE TITLE
support raw strings

### ISSUE THREAD

**Issue by kevinushey** [r-lib/tree-sitter-r#34]
For example:

```
$ echo 'r"(raw "quotes" string)"' > raw-string.R; tree-sitter parse raw-string.R
(program [0, 0] - [1, 0]
  (identifier [0, 0] - [0, 1])
  (string [0, 1] - [0, 8])
  (identifier [0, 8] - [0, 14])
  (string [0, 14] - [0, 24]))
```

As an aside, R is very permissive for raw strings; e.g. these are all valid raw strings:

```
    ## More raw strings:
     r"{(\1\2)}"
     r"(use both "double" and 'single' quotes)"
     R"---[\1--]-]---"
```

**Comment by kevinushey** [comment]
It's unlikely we'll be able to describe R's raw strings directly in `grammar.js`; however, we should be able to define a custom scanner here:

https://tree-sitter.github.io/tree-sitter/creating-parsers#external-scanners

See, for example:

https://github.com/tree-sitter/tree-sitter-cpp/blob/master/src/scanner.cc
https://github.com/tree-sitter/tree-sitter-cpp/blob/master/grammar.js#L26-L2

**Comment by jimhester** [comment]
Assuming I am reading the code at https://github.com/wch/r-source/blob/52b730f217c12ba3d95dee0cd1f330d1977b5ea3/src/main/gram.y#L3102 correctly https://regex101.com/r/DPmEw0/1 gets us pretty close. The main thing I think you would have to do is add an additional check that the opening bracket matches the closing one.

**Comment by kevinushey** [comment]
It looks like tree-sitter doesn't support regular expressions containing backreferences:

```
$ tree-sitter generate
Error processing rule string_token1

Caused by:
    regex parse error:
        [rR](['"])(-*)\[.*\]\2\1
                            ^^
    error: backreferences are not supported
```
