### ISSUE TITLE
Wrong node extents within braces on `main`

### ISSUE THREAD

**Issue by lionel-** [r-lib/tree-sitter-r#44]
I encountered this bug with the main branch of `tree-sitter-r`. This snippet:

```r
{
  1
2
  3
}
```

Is parsed as:

```
[program] [0, 0] - [5, 0]
  [brace_list] [0, 0] - [4, 1]
    [float] [1, 2] - [1, 3]
    [float] [1, 3] - [2, 1]
    [float] [3, 2] - [3, 3]
```

Note how the second number node overlaps with the previous line.

With the `next` branch it's correctly parsed as:

```
[program] [0, 0] - [5, 0]
  [{] [0, 0] - [4, 1]
    body: [float] [1, 2] - [1, 3]
    body: [float] [2, 0] - [2, 1]
    body: [float] [3, 2] - [3, 3]
```

I'm posting this in case you would like to add a unit test for this. It looks like the current tests do not include the node extents, I'm not sure if it's easy or desirable to test for this.

**Comment by kevinushey** [comment]
PRs are definitely appreciated, but I don't intend to spend any more time maintaining the rules on `main` (all active development is happening in `next`).

**Comment by lionel-** [comment]
yup I was wondering if we wanted to add unit tests for node extents on the next branch. This is currently completely uncovered by the tests which seems a bit surprising, but that's how tree-sitter does things apparently. Feel free to close the issue if extents tests are not appropriate or feasible.

**Comment by DavisVaughan** [comment]
Much easier to add a test for this now that our snapshot tests show the locations!
