### ISSUE TITLE
R code to BNF

### ISSUE THREAD

**Issue by mytarmail** [r-lib/tree-sitter-r#51]
Hello! I know very little about parsers and everything else, which is why my question might be stupid.

I need to translate R code into BNF grammar, can I do it with your package?
If so, I would be very grateful for a small example
Thank you.

**Comment by kevinushey** [comment]
Sorry, but no, this project won't help with that. You could try translating manually from the grammar file here:

https://github.com/wch/r-source/blob/trunk/src/main/gram.y#L393-L563
