### ISSUE TITLE
Raw string literals are parsed incorrectly

### ISSUE THREAD

**Issue by klmr** [r-lib/tree-sitter-r#60]
## Actual behaviour

When using the syntax highlighting hints from R treesitter, raw string literals aren’t parsed correctly, and regular quotes inside the 
raw string literal terminate the string:

![Screenshot 2023-10-27 at 11 40 28](https://github.com/r-lib/tree-sitter-r/assets/38931/a1c0b1f1-ffd0-4417-83b0-873f2691de69)

(Screenshot taken in NeoVim v0.9.1. Without r-tree-sitter, the literal is highlighted correctly.)

## Expected behaviour

![Screenshot 2023-10-27 at 11 42 29](https://github.com/r-lib/tree-sitter-r/assets/38931/1cf1e811-d45e-4aa2-8c70-7addb9139efc)

**Comment by kevinushey** [comment]
This might be resolved in the [next](https://github.com/r-lib/tree-sitter-r/tree/next) branch, but note that the grammar there is substantially different. It's possible we could port some of the changes from there back to main.

**Comment by DavisVaughan** [comment]
Can confirm that in the next branch this is fixed. We are working towards getting that merged into `main`

``` r
library(treesitter, warn.conflicts = FALSE)

text <- "
foo = r'['hello]'
foobar # not inside
"

language <- treesitterr::language()
parser <- parser(language)

parser_parse(parser, text)
#> <tree_sitter_tree>
#> 
#> ── S-Expression ────────────────────────────────────────────────────────────────────────────────────────────────────
#> (program [(1, 0), (3, 0)]
#>   (equals_assignment [(1, 0), (1, 17)]
#>     lhs: (identifier [(1, 0), (1, 3)])
#>     operator: "=" [(1, 4), (1, 5)]
#>     rhs: (string [(1, 6), (1, 17)])
#>   )
#>   (identifier [(2, 0), (2, 6)])
#>   (comment [(2, 7), (2, 19)])
#> )
#> 
#> ── Text ────────────────────────────────────────────────────────────────────────────────────────────────────────────
#> foo = r'['hello]'
#> foobar # not inside
```
