### ISSUE TITLE
String literals with some Unicode escapes are parsed incorrectly

### ISSUE THREAD

**Issue by klmr** [r-lib/tree-sitter-r#61]
## Actual behaviour

When using the syntax highlighting hints from R treesitter, some (but not all!) Unicode escape sequences inside string literals are parsed incorrectly and cause all subsequent lexemes to be classified incorrectly.

I’m unsure which combination exactly causes this behaviour; in the example below, removing either `\u02` or `\uf101` rectifies the behaviour. The combination of both is required to trigger the bug.

![Screenshot 2023-10-27 at 11 41 09](https://github.com/r-lib/tree-sitter-r/assets/38931/8d48fefb-cdfb-4b55-b97b-b4830ea55f67)

(Screenshot taken in NeoVim v0.9.1. Without r-tree-sitter, the literal is highlighted correctly.)

## Expected behaviour

![Screenshot 2023-10-27 at 11 42 05](https://github.com/r-lib/tree-sitter-r/assets/38931/129464e0-89d8-4070-a8ee-41b20a4f546e)

**Comment by kevinushey** [comment]
This may also be resolved in the [next](https://github.com/r-lib/tree-sitter-r/tree/next) branch.

**Comment by DavisVaughan** [comment]
This looks to be resolved by the next branch.
