### ISSUE TITLE
"..i" node name gives problems with tree-sitter-node

### ISSUE THREAD

**Issue by rien** [r-lib/tree-sitter-r#62]
The `..i` token defined here: https://github.com/r-lib/tree-sitter-r/blob/1e9eaa9af98c9ac92e3d1e1713a453eef488fe36/grammar.js#L304

Causes an error when this parser is loaded in `tree-sitter-node`, because it creates a class for each syntax node and a dot (`.`) is illegal in a class name.

Is it possible to use a different name (without special characters) for this token?

**Comment by kevinushey** [comment]
Thanks; I think that's reasonable. Just need to figure out a good name...

**Comment by rien** [comment]
How about `argument_reference`? I'll draft a PR later today.
