### ISSUE TITLE
List in 'nvim-treesitter' plugin

### ISSUE THREAD

**Issue by echasnovski** [r-lib/tree-sitter-r#7]
[nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) is a Neovim plugin that adds some tree-sitter based features to Neovim. It has many [supported languages](https://github.com/nvim-treesitter/nvim-treesitter#supported-languages) but R is currently not one of them. What do you think about adding this repository as the main source of R's tree-sitter functionality? This will enable more streamlined usage of your work in Neovim.

To add this repository as a source of R's tree-sitter grammar, it means at least:
- Adding this repository with a maintainer's nickname to the README.
- Adding [parser configuration](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lua/nvim-treesitter/parsers.lua).
- Add queries (highlights, locals, etc.) to a certain [directory](https://github.com/nvim-treesitter/nvim-treesitter/tree/master/queries).

If that is OK with you, I can make those changes myself.

**Comment by jimhester** [comment]
Yeah, sounds great, I use neovim myself for writing R code, so this definitely would be personally useful!

**Comment by theHamsta** [comment]
@jimhester We will soon switch to the new tree-sitter ABI 0.19.X https://github.com/neovim/neovim/pull/14076 . You could help nvim users a lot by releasing a new parser generated with version 0.19.3 of tree-sitter CLI because then they will be able to install the parser directly from the C files.

**Comment by jimhester** [comment]
@theHamsta Just re-generated the parser with tree-sitter 0.19.3 in https://github.com/r-lib/tree-sitter-r/commit/9a7f8d6429a48116f4c757ec0abbe42ac87c1f8e

**Comment by inventionate** [comment]
Thank you very much. This works brilliantly!

**Comment by echasnovski** [comment]
Closing as it is supported in latest master branch.

**Comment by ECon87** [comment]
Hi,

I am new to neovim, and this is probably the wrong repo. But has the parser been added in nvim-treesitter?
I have installed the "r" module, but nothing is highlighted. I have enabled highlighting in the init.vim file.

Thanks.
