### ISSUE TITLE
Possible improvements

### ISSUE THREAD

**Issue by inventionate** [r-lib/tree-sitter-r#8]
First of all, thank you for the helpful tree sitter grammar.

I mentioned it in connection with nvim-r and it has opened up potential areas of improvement that I would like to point out here:  jalvesaq/Nvim-R#577. There may be opportunities to take these up and discuss or implement them.

**Comment by aspeddro** [comment]
To keep this topic updated

### Within the scope of tree-sitter

- [ ] The arguments first and second are highlighted only in the function header, not in its body.



- [ ] Special characters within strings are not recognized. (#23)

- [x] `TRUE` and `FALSE` should be highlighted as Boolean and not as Keyword (#17)

   
### Currently outside the scope of tree-sitter

> The string "abc" is only underlined. The color indicates the type of spelling mistake, but it was lost.

   Tree-sitter does not identify typo
    
> Because Treesitter knows the structure of the code, I think it should highlight as error the nothing() above the function definition because R would not found it if the code was run.

Tree-sitter is not able to do a semantic analysis, this is a job for LSP or a lint

> Similarly, the keyword fread should be highlighted as a function only after library(data.table) because only then it would be available.

   Same above

> The highlight of the NOTE was messed up in (2). The treesitter replaced the foreground color, but not the background one.

   Highlight `"NOTE"` is not implemented in this tree-sitter. Probably another plugin is making this standout. In general tree-sitter parsers cover the grammar of the language, TODO Comments are a kind of extension

**Comment by joiharalds** [comment]
>> The highlight of the NOTE was messed up in (2). The treesitter replaced the foreground color, but not the background one.

>Highlight "NOTE" is not implemented in this tree-sitter. Probably another plugin is making this standout. In general tree-sitter parsers cover the grammar of the language, TODO Comments are a kind of extension

Language injection has been implemented in Treesitter and a comment parser extension is available:
https://github.com/nvim-treesitter/nvim-treesitter/issues/236
https://github.com/stsewd/tree-sitter-comment

So to get this working for R the R parser needs to handle language injection and support needs to be added for R in the comment parser?

**Comment by aspeddro** [comment]
injections are defined an a file named `injections.scm`

1. Create a `injections.scm` at `~/.config/nvim/after/queries/r/injections.scm`
2. Mappe the node that will be injected.
3. In the example below, the `tree-sitter-comment` (`@comment`) will be injected into the `comment` node.

Example:

```query
(comment) @comment
```

![image](https://user-images.githubusercontent.com/16160544/159100382-6f0cfacb-1fae-4f35-87a0-e8af9df3a7b6.png)


More details see https://github.com/nvim-treesitter/nvim-treesitter/blob/master/CONTRIBUTING.md#injections

**Comment by DavisVaughan** [comment]
It seems like the `next` branch supports args being identified both in the function signature and their usage in function bodies.  It also supports escape sequence string subsections and `boolean` highlights for `TRUE` and `FALSE` so I'm going to close this

<img width="642" alt="Screenshot 2024-06-11 at 12 26 21 PM" src="https://github.com/r-lib/tree-sitter-r/assets/19150088/0cd83e27-a65e-420e-9c2d-186bbc6c9ab8">
