### ISSUE TITLE
Add queries/tags.scm to support code navigation on GitHub

### ISSUE THREAD

**Issue by hturner** [r-lib/tree-sitter-r#80]
GitHub has the ability to navigate across code, e.g. clicking on a function name to jump to the definition. Unfortunately, this is not available for R: https://docs.github.com/en/repositories/working-with-files/using-files/navigating-code-on-github.

It seems there is potential to contribute the necessary functionality, see this discussion about doing this for Common Lisp: https://github.com/orgs/community/discussions/55704. The GitHub implementation relies on Tree-sitter, which has R support thanks to the work here. However, one thing that is missing is the queries/tags.scm file.

I'm not sure how hard it would be to create such a tags file. It may help to look at examples, e.g. https://github.com/elixir-lang/tree-sitter-elixir/blob/main/queries/tags.scm or Deepayan Sarkar's rcodesearch, which has the jump to definition functionality: https://deepayan.github.io/experiments/rcodesearch/display.html?file=library%2Fbase%2FR%2FcolSums.R.

**Comment by DavisVaughan** [comment]
We're doing some heavy work on tree-sitter-r in the `next` branch, I'll make sure we add this over there after things stabilize
