### ISSUE TITLE
Incorrect `|>` , `+` precedence combination

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/tree-sitter-r#81]
```r
x |> foo() + baz()
```

gives

```
(program 
  (|> 
    lhs: (identifier) 
    rhs: (+ 
      lhs: (call 
        (identifier) 
         arguments: (arguments)) 
      rhs: (call 
         (identifier) 
         arguments: (arguments)))))
```

should be

```
(program
  (+
    (|>
      (identifier)
      (call
        (identifier)
        (arguments)))
    (call
      (identifier)
      (arguments)))
```

i.e. pipe happens first internally, then `+` happens at the end

**Comment by DavisVaughan** [comment]
Note pipe is _after_ `+` in the R prec table
https://github.com/wch/r-source/blob/36008873fb8ca2af3bdaaff418dbade5f7bce118/src/main/gram.y#L427-L429

But our prec table has it _before_ `+`
https://github.com/r-lib/tree-sitter-r/blob/af5fef876ac2577e3d0b6e5c88faeae8cb04d815/grammar.js#L56-L68

**Comment by kevinushey** [comment]
Possibly related to https://github.com/wch/r-source/commit/e9f7b6c363a97fff6c41fa2d6e206dce0002edc8? Apparently the precedence of those operators did change a bit over time?

**Comment by DavisVaughan** [comment]
Makes sense!
