### ISSUE TITLE
`$` and `@` should not allow arbitrary expressions on the RHS

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/tree-sitter-r#82]
Only strings and symbols
https://github.com/wch/r-source/blob/36008873fb8ca2af3bdaaff418dbade5f7bce118/src/main/gram.y#L512-L515

```r
foo${hi}
```

gives

```
(program ($ lhs: (identifier) rhs: ({ body: (identifier))))
```

but really that should probably error

**Comment by kevinushey** [comment]
Having arbitrary expressions was the easiest way to support `foo$bar$baz` or `foo$bar()$baz[[1]]$bam`, but it still might be worth clamping those down a bit.
