### ISSUE TITLE
Do a full once over comparison of `main` vs `next` before merging

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/tree-sitter-r#98]
To see if we are losing anything important, for example:
- On `main` I think it marks `escape_sequence`s within strings separately which can then be highlighted specially by editors
- `switch()` used to be its own node type, but is now "just" another R expression - should we retain a separate node type for it? https://github.com/r-lib/tree-sitter-r/blob/c55f8b4dfaa32c80ddef6c0ac0e79b05cb0cbf57/grammar.js#L142 Related to #84 

Update: I have done the once over and I think these are the only 2 important things to consider

**Comment by clason** [comment]
Yes, but with a no longer valid regex, see #99 ;)
